### ISSUE TITLE
Initialization error -  Cannot read property 'brunchPluginName' of null

### ISSUE THREAD

**Issue by recs182** [nblackburn/brunch-with-vue#3]
When I try to run brunch using this skeleton I have this error, I tried delete node_modules folder and reinstall all modules but didn't work.

My node version is 6.9.1 and npm is 3.10.8...

Using **loggy_stacks** it's what i have:
```
brunch watch --server LOGGY_STACKS=true
Brunch: Local install exists, but failed to load it. Continuing with global install: { Error: ENOENT: no such file or directory, uv_chdir
  at Error (native)
  at process.chdir (Z:\WebPages\dev_renan\piadasinter\node_modules\graceful-fs\polyfills.js:21:9)
  at watch (Z:\WebPages\dev_renan\piadasinter\node_modules\brunch\lib\watch.js:376:15)
  at start (Z:\WebPages\dev_renan\piadasinter\node_modules\brunch\lib\index.js:44:10)
  at Command.listener (Z:\WebPages\dev_renan\piadasinter\node_modules\commander\index.js:301:8)
  at emitTwo (events.js:106:13)
  at Command.emit (events.js:191:7)
  at Command.parseArgs (Z:\WebPages\dev_renan\piadasinter\node_modules\commander\index.js:615:12)
  at Command.parse (Z:\WebPages\dev_renan\piadasinter\node_modules\commander\index.js:458:21)
  at Object.exports.run (Z:\WebPages\dev_renan\piadasinter\node_modules\brunch\lib\commands.js:89:11)
  at loadBrunch (C:\Users\Usuário\AppData\Roaming\npm\node_modules\brunch\bin\brunch:65:37)
  at Object.<anonymous> (C:\Users\Usuário\AppData\Roaming\npm\node_modules\brunch\bin\brunch:75:5)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.runMain (module.js:604:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3
 errno: -4058, code: 'ENOENT', syscall: 'uv_chdir' }
C:\Users\Usuário\AppData\Roaming\npm\node_modules\brunch\node_modules\graceful-fs\polyfills.js:21
  chdir.call(process, d)
        ^

Error: ENOENT: no such file or directory, uv_chdir
  at Error (native)
  at process.chdir (C:\Users\Usuário\AppData\Roaming\npm\node_modules\brunch\node_modules\graceful-fs\polyfills.js:21:9)
  at watch (C:\Users\Usuário\AppData\Roaming\npm\node_modules\brunch\lib\watch.js:425:15)
  at start (C:\Users\Usuário\AppData\Roaming\npm\node_modules\brunch\lib\index.js:45:10)
  at Command.listener (C:\Users\Usuário\AppData\Roaming\npm\node_modules\brunch\node_modules\commander\index.js:301:8)
  at emitTwo (events.js:106:13)
  at Command.emit (events.js:191:7)
  at Command.parseArgs (C:\Users\Usuário\AppData\Roaming\npm\node_modules\brunch\node_modules\commander\index.js:615:12)
  at Command.parse (C:\Users\Usuário\AppData\Roaming\npm\node_modules\brunch\node_modules\commander\index.js:458:21)
  at Object.exports.run (C:\Users\Usuário\AppData\Roaming\npm\node_modules\brunch\lib\cli.js:123:11)
  at Object.<anonymous> (C:\Users\Usuário\AppData\Roaming\npm\node_modules\brunch\lib\run-cli.js:3:18)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.runMain (module.js:604:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3
```

**Comment by nicooga** [comment]
Having the same issue on linux. npm 3.10.3 and node v6.5.0

**Comment by tomquirk** [comment]
+1
